### ISSUE TITLE
[Feature Request] Allow the configuration of the overlay icons and fonts

### ISSUE THREAD

**Issue by adaliszk** [hetima/DSP_LSTM#20]
Hi, first and foremost:
THANK YOU FOR THE FANTASTIC WORK WITH THE MOD!

I want to request a - hopefully small - configuration option: _As a player with large logistic centres, I would like to change the icon sizes and the static indicator font-size so that I can have a more compact overview of logistic hubs with many stations beside each other._

I would not mind contributing, but I am a total newbie to modding.

It looks to me that the relevant code might be in the [StationSignRenderer.cs:177](https://github.com/hetima/DSP_LSTM/blob/8ffe6a1e121177976a0dab6701a4a7b1fc8b108c/LSTM/StationSignRenderer.cs#L177), where the size is set to the relative zoom level. Given how there is already a reference to the station in question, perhaps adding the options through the available UI within the stations could be a fascinating solution; however, it looks like the preferred way would be a configuration option within the mod files.

**Comment by hetima** [comment]
Added (hidden) configuration to change icon size in 0.8.1.  

|Key|Type|Default|Description|
|---|---|---|---|
|stationInfoIconSize|float|10.0|Station Info icon size. min=5.0 max=15.0. default is 10.0f|

Also, the display method of icons has been improved so that they are not unnaturally large. So maybe you don't have to change configuration.

thanks

**Comment by adaliszk** [comment]
Thank you for the quick implementation!
Indeed the default is better; for me, around 8 looks excellent with dense hubs.
The bonus is that with Giga Logistic Stations (another mod), the minimum 5 makes it great to overview.
